[package]
name = "wasmedge-piper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.120"
wasmedge-wasi-nn = "0.8.0"
